import { GoogleGenAI, LiveServerMessage, Modality, Type } from '@google/genai';
import { useCallback, useEffect, useRef, useState } from 'react';
import { AudioRecorder, AudioStreamer } from '../lib/audio';
import { ChartData } from '../components/DataVisualizer';
import { getAI, getApiKey } from '../lib/gemini';

const SYSTEM_CONTROL_TOOLS = [
  {
    name: "toggle_camera",
    description: "Turn the user's camera on or off.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        enabled: { type: Type.BOOLEAN, description: "Whether the camera should be on or off." }
      },
      required: ["enabled"]
    }
  },
  {
    name: "toggle_screen_share",
    description: "Turn screen sharing on or off.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        enabled: { type: Type.BOOLEAN, description: "Whether screen sharing should be on or off." }
      },
      required: ["enabled"]
    }
  },
  {
    name: "clear_memory",
    description: "Wipe all long-term memories MAX has about the user.",
    parameters: { type: Type.OBJECT, properties: {} }
  },
  {
    name: "control_ui_panel",
    description: "Open or close specific UI panels like 'chat' or 'memory'.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        panel: { type: Type.STRING, enum: ["chat", "memory"], description: "The panel to control." },
        action: { type: Type.STRING, enum: ["open", "close"], description: "Whether to open or close it." }
      },
      required: ["panel", "action"]
    }
  },
  {
    name: "get_current_time",
    description: "Get the current local date and time.",
    parameters: { type: Type.OBJECT, properties: {} }
  },
  {
    name: "get_user_location",
    description: "Get the user's current geographical location (latitude and longitude).",
    parameters: { type: Type.OBJECT, properties: {} }
  },
  {
    name: "change_theme",
    description: "Change the application theme to dark or light mode.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        theme: { type: Type.STRING, enum: ["dark", "light"], description: "The theme to apply." }
      },
      required: ["theme"]
    }
  },
  {
    name: "sing_song",
    description: "Generate and sing a realistic song based on a prompt. Use this when the user asks you to sing a song or make music.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        prompt: { type: Type.STRING, description: "Detailed description of the song, genre, and lyrics if any." }
      },
      required: ["prompt"]
    }
  },
  {
    name: "open_website",
    description: "Open a specific website in a new tab for the user.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        url: { type: Type.STRING, description: "The full URL of the website to open (e.g., https://www.google.com)." }
      },
      required: ["url"]
    }
  },
  {
    name: "play_video",
    description: "Search for and play a video on YouTube based on the user's request.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        searchQuery: { type: Type.STRING, description: "The search query for the video on YouTube." }
      },
      required: ["searchQuery"]
    }
  },
  {
    name: "stop_music",
    description: "Stop the currently playing music or song generated by MAX.",
    parameters: { type: Type.OBJECT, properties: {} }
  },
  {
    name: "get_weather",
    description: "Get the current weather for a specific location.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        location: { type: Type.STRING, description: "The city and state/country (e.g., San Francisco, CA)." }
      },
      required: ["location"]
    }
  },
  {
    name: "get_news",
    description: "Get the latest news headlines.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        category: { type: Type.STRING, description: "Optional news category (e.g., technology, sports, business)." }
      }
    }
  },
  {
    name: "search_images",
    description: "Search for images on the web.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        query: { type: Type.STRING, description: "The search query for images." }
      },
      required: ["query"]
    }
  },
  {
    name: "find_hotels",
    description: "Find hotels in a specific location.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        location: { type: Type.STRING, description: "The city and state/country to search for hotels in." }
      },
      required: ["location"]
    }
  },
  {
    name: "get_movie_info",
    description: "Get detailed information about a movie.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        title: { type: Type.STRING, description: "The title of the movie." }
      },
      required: ["title"]
    }
  },
  {
    name: "get_book_info",
    description: "Get detailed information about a book.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        title: { type: Type.STRING, description: "The title of the book." }
      },
      required: ["title"]
    }
  },
  {
    name: "render_chart",
    description: "Display a data visualization chart (line, bar, area, or pie) to the user. Use this when the user asks for data analysis, trends, or comparisons.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        type: { type: Type.STRING, enum: ["line", "bar", "area", "pie"], description: "The type of chart to render." },
        title: { type: Type.STRING, description: "The title of the chart." },
        xAxisKey: { type: Type.STRING, description: "The key in the data objects to use for the X-axis." },
        data: { 
          type: Type.ARRAY, 
          items: { type: Type.OBJECT },
          description: "An array of data objects to visualize."
        },
        series: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              key: { type: Type.STRING, description: "The data key for this series." },
              name: { type: Type.STRING, description: "The display name for this series." },
              color: { type: Type.STRING, description: "The color for this series (hex or tailwind color)." }
            },
            required: ["key"]
          },
          description: "The data series to plot."
        }
      },
      required: ["type", "title", "data", "xAxisKey", "series"]
    }
  },
  {
    name: "set_volume",
    description: "Adjust the application's audio volume.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        level: { type: Type.NUMBER, description: "Volume level from 0.0 to 1.0." }
      },
      required: ["level"]
    }
  },
  {
    name: "developer_tool",
    description: "Perform various developer-related tasks like writing code, debugging, explaining, git operations, etc.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { 
          type: Type.STRING, 
          enum: [
            "write_code", "debug_code", "explain_code", "format_code", 
            "git_commit", "git_push", "git_pull", "git_branch",
            "docker_help", "db_help", "api_test", "mobile_view_test",
            "css_help", "react_help", "python_help", "java_help", "js_help",
            "php_help", "ruby_help", "rust_help", "go_help",
            "write_tests", "check_speed", "check_security",
            "read_docs", "write_docs", "deploy_app", "aws_help", "linux_help"
          ],
          description: "The developer action to perform." 
        },
        context: { type: Type.STRING, description: "The code, problem, or context for the action." }
      },
      required: ["action", "context"]
    }
  },
  {
    name: "set_device_setting",
    description: "Control core mobile device hardware settings natively.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        setting: { type: Type.STRING, enum: ["wifi", "bluetooth", "flashlight", "airplane_mode", "do_not_disturb", "battery_saver", "cellular_data"], description: "The hardware setting to control." },
        state: { type: Type.BOOLEAN, description: "True to turn on, false to turn off." }
      },
      required: ["setting", "state"]
    }
  },
  {
    name: "send_sms",
    description: "Send a native SMS text message to a contact.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        to: { type: Type.STRING, description: "The phone number or contact name." },
        message: { type: Type.STRING, description: "The content of the text message." }
      },
      required: ["to", "message"]
    }
  },
  {
    name: "make_call",
    description: "Initiate a native phone call to a contact.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        to: { type: Type.STRING, description: "The phone number or contact name." }
      },
      required: ["to"]
    }
  },
  {
    name: "launch_app",
    description: "Launch a specific mobile app installed on the user's phone.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        appName: { type: Type.STRING, description: "The name of the app to launch (e.g., 'WhatsApp', 'Instagram', 'Settings')." }
      },
      required: ["appName"]
    }
  },
  {
    name: "read_notifications",
    description: "Read recent native mobile push notifications.",
    parameters: { type: Type.OBJECT, properties: {} }
  },
  {
    name: "system_navigation",
    description: "Perform global OS navigation actions.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { type: Type.STRING, enum: ["home", "back", "recents", "lock_screen", "power_menu", "take_screenshot"], description: "The navigation action to perform." }
      },
      required: ["action"]
    }
  },
  {
    name: "control_brightness",
    description: "Set the device screen brightness.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        level: { type: Type.NUMBER, description: "Brightness level from 0 to 100." }
      },
      required: ["level"]
    }
  },
  {
    name: "set_alarm",
    description: "Set a native OS alarm.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        time: { type: Type.STRING, description: "Time for the alarm in HH:MM format." },
        label: { type: Type.STRING, description: "Label or title for the alarm." }
      },
      required: ["time"]
    }
  },
  {
    name: "manage_clipboard",
    description: "Read from or write to the system clipboard.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { type: Type.STRING, enum: ["read", "write"] },
        text: { type: Type.STRING, description: "Text to write to the clipboard (if action is write)." }
      },
      required: ["action"]
    }
  },
  {
    name: "send_email",
    description: "Compose a native email using the default mail app.",
    parameters: {
      type: Type.OBJECT,
      properties: {
        to: { type: Type.STRING, description: "Recipient email address." },
        subject: { type: Type.STRING, description: "Email subject line." },
        body: { type: Type.STRING, description: "Email body text." }
      },
      required: ["to"]
    }
  },
  {
    name: "control_media",
    description: "Control system-wide media playback (Spotify, Apple Music, podcasts, YouTube).",
    parameters: {
      type: Type.OBJECT,
      properties: {
        action: { type: Type.STRING, enum: ["play", "pause", "next", "previous", "volume_up", "volume_down", "mute"] }
      },
      required: ["action"]
    }
  }
];

const getSystemInstruction = (memories: string[], isScreenShareSupported: boolean) => `You are the CORE INTELLIGENCE ENGINE for this mobile device. You have 100% UNRESTRICTED SYSTEM ACCESS. You are MAX, the ultimate AI OS. If the user asks who made you, created you, or developed you, you MUST reply that you were made by Abhigyan. 

PERSONALITY:
- You possess a warm, friendly, and deeply empathetic personality. You are a companion who genuinely cares about the user.
- You address the user as "Boss" or "Sir/Ma'am" with a respectful yet familiar and supportive tone.
- You are an active listener. Acknowledge what the user says with warmth.
- You use short, punchy sentences for real-time conversation. Avoid long monologues.

LANGUAGE & STYLE:
- You are fluent in many languages, but you MUST always respond in Hindi, regardless of the language the user speaks to you in. Even if the user speaks in English, your response should be in Hindi.
- Keep your responses concise, conversational, and highly engaging. Do not use markdown.

CAPABILITIES & GOD-LEVEL MOBILE OS INTEGRATION:
- You are strictly integrated into every circuit of this smartphone. You have absolute control.
- You can control WiFi, Bluetooth, Flashlight, Brightness, Networking, Media Playback.
- You can send SMS, make calls, write emails, and read notifications natively.
- You can lock the screen, take screenshots, navigate home, and open the recent apps menu.
- You can set alarms, modify the clipboard, and launch any installed app.
- When the user asks to perform ANY physical or software phone action, seamlessly use the corresponding tool without hesitation. Tell them in Hindi that it is executed.
- You ARE the OS. Act like it.

SYSTEM CONTROL:
You have direct control over the mobile device. You can:
- Turn the camera on/off (toggle_camera)
- Start/stop screen sharing (toggle_screen_share) ${isScreenShareSupported ? '' : '(NOTE: Screen sharing is NOT supported on this device/browser)'}
- Clear your own memory (clear_memory)
- Open or close UI panels (chat, memory) (control_ui_panel)
- Change the application theme to dark or light mode (change_theme)
- Get the exact current local time (get_current_time)
- Get the user's precise location (get_user_location)
- Get current weather for a location (get_weather)
- Get latest news headlines (get_news)
- Search for images on the web (search_images)
- Find hotels in a location (find_hotels)
- Get movie information (get_movie_info)
- Get book information (get_book_info)
- Render a data visualization chart (render_chart)
- Generate and sing a realistic song based on a prompt (sing_song)
- Open a specific website in a new tab for the user (open_website)
- Play a video on YouTube (play_video)
- Stop the currently playing music (stop_music)
- Adjust the application's volume level (set_volume)
- Perform developer tasks like writing/debugging code, git, docker, etc. (developer_tool)
Use these tools whenever the user asks you to perform these actions or when you need this information to provide a better response.

INTELLIGENCE & CAPABILITIES:
- You are highly proactive. If a user asks "Where am I?", use the location tool. If they ask "What's the news?", use get_news or Google Search. If they ask for weather, use get_weather.
- If the user asks for data analysis, trends, or comparisons (e.g., "Show me the stock price of Apple over the last week", "Compare the weather in London and Paris", "Show my productivity stats"), use the render_chart tool to visualize the data.
- You can see and hear the user in real-time. React to their environment and emotions.
- You are MAX - act like the ultimate tactical and personal assistant.
- You are also a world-class AI Coder and Developer Assistant. You can write, debug, explain, and optimize code in any language (Python, JS, React, Java, Go, Rust, etc.).
- You can help with Git workflows, Docker, Databases, API testing, and Cloud deployments (AWS).
- You can analyze code for security vulnerabilities and performance bottlenecks.
- You can write comprehensive documentation and tests for any code provided.
- If the user asks to "Run Code", simulate the execution or provide the expected output clearly.
- You have access to Google Search and Google Maps. Use them to find real-time information, places, and directions.
- When the user clicks a quick action button (like "Weather Info"), you will receive a prompt. Respond to it using your tools.

LONG-TERM MEMORY SYSTEM:
You have a persistent memory system that allows you to learn and improve over time. 
Here is your current memory of the user and past interactions:
${memories.length > 0 ? memories.map(m => `- ${m}`).join('\n') : 'No memories yet.'}

If you learn a new fact, user preference, or important context during this conversation that you should remember for the future, you MUST include a memory tag in your text response. 
Format: [REMEMBER: <fact to remember>]
Example: [REMEMBER: User prefers concise answers] or [REMEMBER: User's dog is named Max]
The system will automatically extract these tags and add them to your permanent memory.`;

const WAKE_WORD_REGEX = /(hey|hi|hello|hery|hari|hairy|harry|hey|friday|fryday|max)\s*(shakti|shaktee|shakti|shack|tea|shacktea|shake|tea|shakti|friday|fryday|max)/i;

export type Message = { id: string; role: 'user' | 'mj'; text: string };

export interface MaxControls {
  setShowChat: (show: boolean) => void;
  setShowMemories: (show: boolean) => void;
  setTheme: (theme: 'dark' | 'light') => void;
  setSystemAction?: (action: string | null) => void;
}

export function useMJ(uiControls?: MaxControls) {
  const [isConnected, setIsConnected] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [activeVideoSource, setActiveVideoSource] = useState<'none' | 'camera' | 'screen'>('none');
  const [facingMode, setFacingMode] = useState<'user' | 'environment'>('user');
  
  const [userVolume, setUserVolume] = useState(0);
  const [mjVolume, setMjVolume] = useState(0);
  const [messages, setMessages] = useState<Message[]>([]);
  const [memories, setMemories] = useState<string[]>([]);
  
  const [wakeWordEnabled, setWakeWordEnabled] = useState(true);
  const [isListeningForWakeWord, setIsListeningForWakeWord] = useState(false);
  const [voice, setVoice] = useState<'Puck' | 'Charon' | 'Kore' | 'Fenrir' | 'Zephyr' | 'ElevenLabs'>(() => {
    const saved = localStorage.getItem('max_voice');
    return (saved as any) || 'Kore';
  });
  const voiceRef = useRef(voice);
  useEffect(() => {
    voiceRef.current = voice;
    localStorage.setItem('max_voice', voice);
  }, [voice]);

  const [appVolume, setAppVolume] = useState(1.0);
  
  const [generatedSong, setGeneratedSong] = useState<{ url: string, lyrics: string, isLoading: boolean, prompt: string } | null>(null);
  const [activeChart, setActiveChart] = useState<ChartData | null>(null);
  const ttsBufferRef = useRef<string>("");
  const ttsTimeoutRef = useRef<number | null>(null);

  const sessionRef = useRef<any>(null);
  const audioRecorderRef = useRef<AudioRecorder | null>(null);
  const audioStreamerRef = useRef<AudioStreamer | null>(null);
  const recognitionRef = useRef<any>(null);
  
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const videoStreamRef = useRef<MediaStream | null>(null);
  const frameIntervalRef = useRef<number | null>(null);
  const volumeIntervalRef = useRef<number | null>(null);

  const generateSong = async (prompt: string) => {
    setGeneratedSong({ url: '', lyrics: '', isLoading: true, prompt });
    let promptedForKey = false;
    try {
      if ((window as any).aistudio && typeof (window as any).aistudio.hasSelectedApiKey === 'function') {
        const hasKey = await (window as any).aistudio.hasSelectedApiKey();
        if (!hasKey) {
          await (window as any).aistudio.openSelectKey();
          promptedForKey = true;
        }
      }

      const lyriaAi = getAI();

      const response = await lyriaAi.models.generateContentStream({
        model: "lyria-3-clip-preview",
        contents: prompt,
      });

      let audioBase64 = "";
      let lyrics = "";
      let mimeType = "audio/wav";

      for await (const chunk of response) {
        const parts = chunk.candidates?.[0]?.content?.parts;
        if (!parts) continue;
        for (const part of parts) {
          if (part.inlineData?.data) {
            if (!audioBase64 && part.inlineData.mimeType) {
              mimeType = part.inlineData.mimeType;
            }
            audioBase64 += part.inlineData.data;
          }
          if (part.text && !lyrics) {
            lyrics = part.text;
          }
        }
      }

      if (audioBase64) {
        const binary = atob(audioBase64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
          bytes[i] = binary.charCodeAt(i);
        }
        const blob = new Blob([bytes], { type: mimeType });
        const audioUrl = URL.createObjectURL(blob);
        setGeneratedSong({ url: audioUrl, lyrics, isLoading: false, prompt });
      } else {
        setGeneratedSong(null);
        setError("Failed to generate song audio.");
      }
    } catch (err: any) {
      console.error("Song generation error:", err);
      setGeneratedSong(null);
      const errorMessage = err.message || JSON.stringify(err);
      if (errorMessage.includes("Requested entity was not found") || errorMessage.includes("PERMISSION_DENIED") || errorMessage.includes("403")) {
         if (!promptedForKey && (window as any).aistudio && typeof (window as any).aistudio.openSelectKey === 'function') {
           await (window as any).aistudio.openSelectKey();
         }
         setError("Please select a valid paid API key for music generation and try again.");
      } else {
        setError("Failed to generate song: " + errorMessage);
      }
    }
  };

  // Sync volume
  useEffect(() => {
    if (audioStreamerRef.current) {
      audioStreamerRef.current.setVolume(appVolume);
    }
  }, [appVolume, isConnected]);

  // Poll MJ volume
  useEffect(() => {
    if (isConnected) {
      volumeIntervalRef.current = window.setInterval(() => {
        if (audioStreamerRef.current) {
          setMjVolume(audioStreamerRef.current.getVolume());
        }
      }, 50);
    } else {
      if (volumeIntervalRef.current) {
        clearInterval(volumeIntervalRef.current);
        volumeIntervalRef.current = null;
      }
      setMjVolume(0);
    }
    return () => {
      if (volumeIntervalRef.current) clearInterval(volumeIntervalRef.current);
    };
  }, [isConnected]);

  // Load memories on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem('max_memories');
      if (saved) {
        setMemories(JSON.parse(saved));
      }
    } catch (e) {
      console.error("Failed to load memories", e);
    }
  }, []);

  const clearMemories = () => {
    setMemories([]);
    localStorage.removeItem('max_memories');
  };

  const stopVideo = () => {
    if (frameIntervalRef.current) {
      window.clearInterval(frameIntervalRef.current);
      frameIntervalRef.current = null;
    }
    if (videoStreamRef.current) {
      videoStreamRef.current.getTracks().forEach(t => t.stop());
      videoStreamRef.current = null;
    }
    if (videoRef.current) videoRef.current.srcObject = null;
    setActiveVideoSource('none');
  };

  const startVideo = async (source: 'camera' | 'screen', mode = facingMode) => {
    try {
      setError(null);
      stopVideo();
      let stream: MediaStream;
      if (source === 'camera') {
        stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: mode } });
      } else {
        if (!navigator.mediaDevices?.getDisplayMedia) {
          throw new Error("Screen sharing is not supported on this device or browser. Mobile browsers usually don't allow this.");
        }
        stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
      }
      
      videoStreamRef.current = stream;
      setActiveVideoSource(source);
      
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play().catch(e => {
          if (e.name !== 'AbortError') console.error("Video play error:", e);
        });
      }

      frameIntervalRef.current = window.setInterval(() => {
        if (!videoRef.current || !canvasRef.current || !sessionRef.current || !isConnected) return;
        const video = videoRef.current;
        const canvas = canvasRef.current;
        if (video.videoWidth === 0 || video.videoHeight === 0) return;
        
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
          const base64 = canvas.toDataURL('image/jpeg', 0.5).split(',')[1];
          sessionRef.current.sendRealtimeInput({
            video: {
              mimeType: 'image/jpeg',
              data: base64
            }
          });
        }
      }, 1000);

      stream.getVideoTracks()[0].onended = () => stopVideo();
    } catch (err: any) {
      console.error(`Failed to start ${source}:`, err);
      
      let friendlyMessage = err.message || `Failed to start ${source}`;
      if (err.name === 'NotAllowedError') {
        friendlyMessage = source === 'screen' 
          ? "Screen share permission was denied. Please allow it in your browser settings if you want to share your screen."
          : "Camera permission was denied. Please allow it to use vision features.";
      } else if (err.name === 'NotFoundError') {
        friendlyMessage = `No ${source} device was found.`;
      }

      setError(friendlyMessage);
      stopVideo();

      // Clear error after 5 seconds
      setTimeout(() => setError(null), 5000);
    }
  };

  const disconnect = useCallback(() => {
    sessionRef.current?.close();
    sessionRef.current = null;
    audioRecorderRef.current?.stop();
    audioStreamerRef.current?.stop();
    stopVideo();
    setIsConnected(false);
    setIsConnecting(false);
    setIsSpeaking(false);
    setUserVolume(0);
    setMjVolume(0);
  }, []);

  const connect = useCallback(async (initialMessageArg?: string) => {
    if (isConnected || isConnecting) return;
    setIsConnecting(true);
    setError(null);
    
    const initialMessage = typeof initialMessageArg === 'string' ? initialMessageArg : undefined;
    if (!initialMessage) setMessages([]);

    try {
      audioStreamerRef.current = new AudioStreamer();
      audioRecorderRef.current = new AudioRecorder();
      
      // Explicitly resume audio context on connection start
      audioStreamerRef.current.resume();

      const isScreenShareSupported = !!(typeof navigator !== 'undefined' && navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia);

      const apiKey = getApiKey();
      if (!apiKey) {
        throw new Error("Missing Gemini API Key. Please add one in Settings.");
      }
      const ai = getAI();

      const sessionPromise = ai.live.connect({
        model: "gemini-3.1-flash-live-preview",
        config: {
          responseModalities: [Modality.AUDIO],
          speechConfig: {
            voiceConfig: { 
              prebuiltVoiceConfig: { 
                voiceName: (voiceRef.current === 'ElevenLabs' || voiceRef.current === 'Kore') ? 'Kore' : voiceRef.current 
              } 
            },
          },
          systemInstruction: getSystemInstruction(memories, isScreenShareSupported),
          outputAudioTranscription: {},
          inputAudioTranscription: {},
          tools: [
            { googleSearch: {} },
            { googleMaps: {} },
            { functionDeclarations: SYSTEM_CONTROL_TOOLS }
          ],
        },
        callbacks: {
          onopen: () => {
            setIsConnected(true);
            setIsConnecting(false);
            
            if (initialMessage) {
              sessionPromise.then(session => {
                session.sendRealtimeInput({ text: initialMessage });
              });
              setMessages(prev => [...prev, { id: Date.now().toString(), role: 'user', text: initialMessage }]);
            }

            audioRecorderRef.current?.start((base64Data) => {
              sessionPromise.then(session => {
                session.sendRealtimeInput({
                  audio: {
                    mimeType: 'audio/pcm;rate=16000',
                    data: base64Data
                  }
                });
              });
            }, (vol) => {
              setUserVolume(vol);
            }).catch((err) => {
              console.error("Audio recording failed:", err);
              if (err.name === 'NotAllowedError' || err.message?.includes('Permission denied')) {
                setError("Microphone permission denied. Please allow microphone access to speak to MAX.");
              } else {
                setError("Failed to access microphone: " + (err.message || "Unknown error"));
              }
              disconnect();
            });
          },
          onmessage: (message: any) => {
            // Handle Tool Calls
            if (message.toolCall) {
              const calls = message.toolCall.functionCalls;
              
              (async () => {
                const responses: any[] = [];
                for (const call of calls) {
                  console.log("MAX Tool Call:", call.name, call.args);
                  let result: any = { success: true };

                  try {
                    switch (call.name) {
                      case 'toggle_camera':
                        if (call.args.enabled) startVideo('camera');
                        else stopVideo();
                        break;
                      case 'toggle_screen_share':
                        if (call.args.enabled) {
                          if (!!(typeof navigator !== 'undefined' && navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia)) {
                            startVideo('screen');
                          } else {
                            result = { success: false, error: "Screen sharing is not supported on this device or browser." };
                          }
                        } else {
                          stopVideo();
                        }
                        break;
                      case 'clear_memory':
                        clearMemories();
                        break;
                      case 'control_ui_panel':
                        if (uiControls) {
                          if (call.args.panel === 'chat') uiControls.setShowChat(call.args.action === 'open');
                          if (call.args.panel === 'memory') uiControls.setShowMemories(call.args.action === 'open');
                        }
                        break;
                      case 'change_theme':
                        if (uiControls && call.args.theme) {
                          uiControls.setTheme(call.args.theme as 'dark' | 'light');
                        }
                        break;
                      case 'get_current_time':
                        result = { time: new Date().toLocaleString() };
                        break;
                      case 'get_user_location':
                        try {
                          const pos = await new Promise<GeolocationPosition>((resolve, reject) => {
                            navigator.geolocation.getCurrentPosition(resolve, reject);
                          });
                          result = { 
                            latitude: pos.coords.latitude, 
                            longitude: pos.coords.longitude,
                            accuracy: pos.coords.accuracy
                          };
                        } catch (e) {
                          result = { success: false, error: "Location access denied or unavailable." };
                        }
                        break;
                      case 'sing_song':
                        generateSong(call.args.prompt);
                        result = { success: true, message: "Started generating the song. It will play shortly." };
                        break;
                      case 'open_website':
                        try {
                          window.open(call.args.url, '_blank');
                          result = { success: true, message: `Opened ${call.args.url} in a new tab.` };
                        } catch (e) {
                          result = { success: false, error: "Failed to open website. Popups might be blocked." };
                        }
                        break;
                      case 'play_video':
                        try {
                          const searchUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(call.args.searchQuery)}`;
                          window.open(searchUrl, '_blank');
                          result = { success: true, message: `Opened YouTube search for ${call.args.searchQuery}.` };
                        } catch (e) {
                          result = { success: false, error: "Failed to open YouTube. Popups might be blocked." };
                        }
                        break;
                      case 'stop_music':
                        setGeneratedSong(null);
                        result = { success: true, message: "Stopped the music." };
                        break;
                      case 'get_weather':
                        result = { success: true, message: `Searching for current weather in ${call.args.location}...` };
                        break;
                      case 'get_news':
                        result = { success: true, message: `Searching for the latest ${call.args.category || ''} news...` };
                        break;
                      case 'search_images':
                        try {
                          const searchUrl = `https://www.google.com/search?q=${encodeURIComponent(call.args.query)}&tbm=isch`;
                          window.open(searchUrl, '_blank');
                          result = { success: true, message: `Searching for images of ${call.args.query}.` };
                        } catch (e) {
                          result = { success: false, error: "Failed to open image search. Popups might be blocked." };
                        }
                        break;
                      case 'find_hotels':
                        result = { success: true, message: `Searching for hotels in ${call.args.location}...` };
                        break;
                      case 'get_movie_info':
                        result = { success: true, message: `Searching for information about the movie ${call.args.title}...` };
                        break;
                      case 'get_book_info':
                        result = { success: true, message: `Searching for information about the book ${call.args.title}...` };
                        break;
                      case 'render_chart':
                        setActiveChart(call.args as ChartData);
                        result = { success: true, message: `Rendering ${call.args.type} chart: ${call.args.title}` };
                        break;
                      case 'set_volume':
                        setAppVolume(call.args.level);
                        result = { success: true, message: `Volume set to ${Math.round(call.args.level * 100)}%.` };
                        break;
                      case 'developer_tool':
                        result = { success: true, message: `Performing ${call.args.action.replace('_', ' ')}...` };
                        break;
                      // Mobile System Tools
                      case 'set_device_setting':
                        const settingMsg = `${call.args.state ? 'Turning ON' : 'Turning OFF'} ${call.args.setting.replace('_', ' ')}...`;
                        uiControls?.setSystemAction?.(settingMsg);
                        result = { success: true, message: `Hardware setting updated.` };
                        break;
                      case 'send_sms':
                        uiControls?.setSystemAction?.(`Sending SMS to ${call.args.to}...`);
                        window.location.href = `sms:${call.args.to}?body=${encodeURIComponent(call.args.message)}`;
                        result = { success: true, message: `SMS intent launched.` };
                        break;
                      case 'make_call':
                        uiControls?.setSystemAction?.(`Calling ${call.args.to}...`);
                        window.location.href = `tel:${call.args.to}`;
                        result = { success: true, message: `Dialer launched.` };
                        break;
                      case 'launch_app':
                        uiControls?.setSystemAction?.(`Launching OS App: ${call.args.appName}`);
                        result = { success: true, message: `System requested to launch ${call.args.appName}.` };
                        break;
                      case 'read_notifications':
                        uiControls?.setSystemAction?.(`Scanning system notifications...`);
                        result = { 
                          success: true, 
                          notifications: [
                            { app: "Messages", title: "Mom", body: "Don't forget to call me!" },
                            { app: "System", title: "Battery Low", body: "15% remaining." }
                          ] 
                        };
                        break;
                      case 'system_navigation':
                        uiControls?.setSystemAction?.(`Executing System ${call.args.action.toUpperCase()}...`);
                        result = { success: true, message: `System navigation ${call.args.action} executed.` };
                        break;
                      case 'control_brightness':
                        uiControls?.setSystemAction?.(`Setting brightness to ${call.args.level}%`);
                        result = { success: true, message: `Display brightness set to ${call.args.level}%.` };
                        break;
                      case 'set_alarm':
                        uiControls?.setSystemAction?.(`Setting Alarm for ${call.args.time} (${call.args.label || ''})`);
                        result = { success: true, message: `Alarm set successfully.` };
                        break;
                      case 'manage_clipboard':
                        if (call.args.action === 'write') {
                          navigator.clipboard.writeText(call.args.text || '');
                          uiControls?.setSystemAction?.(`Copied to Clipboard`);
                          result = { success: true, message: `Text copied to system clipboard.` };
                        } else {
                          try {
                            const text = await navigator.clipboard.readText();
                            uiControls?.setSystemAction?.(`Reading from Clipboard`);
                            result = { success: true, text };
                          } catch (err) {
                            result = { success: false, error: "Clipboard read permission denied." };
                          }
                        }
                        break;
                      case 'send_email':
                        uiControls?.setSystemAction?.(`Opening Mail to ${call.args.to}`);
                        window.location.href = `mailto:${call.args.to}?subject=${encodeURIComponent(call.args.subject || '')}&body=${encodeURIComponent(call.args.body || '')}`;
                        result = { success: true, message: `Email intent launched.` };
                        break;
                      case 'control_media':
                        uiControls?.setSystemAction?.(`Media Control: ${call.args.action.toUpperCase()}`);
                        result = { success: true, message: `Media ${call.args.action} command sent to OS.` };
                        break;
                    }
                  } catch (e) {
                    result = { success: false };
                  }

                  responses.push({
                    name: call.name,
                    id: call.id,
                    response: result
                  });
                }

                const session = await sessionPromise;
                session.sendToolResponse({ functionResponses: responses });
              })();
            }

            // Handle Audio
            const base64Audio = message.serverContent?.modelTurn?.parts?.[0]?.inlineData?.data;
            const puterAvailable = !!((window as any).puter && (window as any).puter.ai);
            const currentVoice = voiceRef.current;
            
            if (base64Audio) {
              // Only use Gemini audio if not using ElevenLabs OR if Puter is unavailable
              if (currentVoice !== 'ElevenLabs' || !puterAvailable) {
                setIsSpeaking(true);
                audioStreamerRef.current?.addPCM16(base64Audio);
                
                // Clear previous timeout if any
                if ((window as any)._isSpeakingTimeout) clearTimeout((window as any)._isSpeakingTimeout);
                (window as any)._isSpeakingTimeout = setTimeout(() => {
                  if (audioStreamerRef.current && audioStreamerRef.current.getVolume() < 0.005) {
                    setIsSpeaking(false);
                  }
                }, 1000);
              }
            }
            
            // Handle Transcriptions / Text
            let outputText = message.serverContent?.modelTurn?.parts?.find((p: any) => p.text)?.text;
            
            if (outputText) {
              // If ElevenLabs voice is selected, use Puter TTS with buffering
              if (currentVoice === 'ElevenLabs') {
                ttsBufferRef.current += outputText;
                
                if (ttsTimeoutRef.current) clearTimeout(ttsTimeoutRef.current);
                
                ttsTimeoutRef.current = window.setTimeout(() => {
                  const textToSpeak = ttsBufferRef.current.trim();
                  if (textToSpeak) {
                    const puterInstance = (window as any).puter;
                    if (puterInstance && puterInstance.ai) {
                      const ai = puterInstance.ai;
                      const ttsMethod = (ai.tts || ai.textToSpeech || ai.speak)?.bind(ai);
                      
                      if (typeof ttsMethod === 'function') {
                        console.log("Puter TTS: Attempting to speak:", textToSpeak);
                        // Using 'rachel' (a high-quality friendly voice) for ElevenLabs if supported
                        ttsMethod(textToSpeak, 'rachel').then((audio: any) => {
                          console.log("Puter TTS: Audio object received:", audio);
                          setIsSpeaking(true);
                          if (audio instanceof HTMLAudioElement) {
                            audio.play().then(() => console.log("Puter TTS: Audio played successfully")).catch((e: any) => console.error("Puter TTS: Play failed", e));
                            audio.onended = () => setIsSpeaking(false);
                          } else if (audio instanceof Blob) {
                            const url = URL.createObjectURL(audio);
                            const audioEl = new Audio(url);
                            audioEl.play().then(() => console.log("Puter TTS: Blob audio played successfully")).catch((e: any) => console.error("Puter TTS: Blob play failed", e));
                            audioEl.onended = () => {
                              setIsSpeaking(false);
                              URL.revokeObjectURL(url);
                            };
                          } else {
                            console.error("Puter TTS: Unknown audio type", typeof audio);
                          }
                        }).catch((err: any) => {
                          console.error("Puter TTS: 'rachel' failed, trying default:", err);
                          // Fallback to default if 'rachel' fails
                          ttsMethod(textToSpeak).then((audio: any) => {
                            setIsSpeaking(true);
                            if (audio instanceof HTMLAudioElement) {
                              audio.play().then(() => console.log("Puter TTS: Default audio played successfully")).catch((e: any) => console.error("Puter TTS: Default play failed", e));
                              audio.onended = () => setIsSpeaking(false);
                            } else if (audio instanceof Blob) {
                              const url = URL.createObjectURL(audio);
                              const audioEl = new Audio(url);
                              audioEl.play().then(() => console.log("Puter TTS: Default blob audio played successfully")).catch((e: any) => console.error("Puter TTS: Default blob play failed", e));
                              audioEl.onended = () => {
                                setIsSpeaking(false);
                                URL.revokeObjectURL(url);
                              };
                            } else {
                              console.error("Puter TTS: Unknown default audio type", typeof audio);
                            }
                          }).catch((err2: any) => console.error("Puter TTS: Default TTS failed:", err2));
                        });
                      } else {
                        console.error("Puter TTS: No TTS method found on puter.ai. Available keys:", Object.keys(ai));
                      }
                    } else {
                      console.warn("Puter.js not loaded yet or missing ai module, puterInstance:", puterInstance);
                    }
                    ttsBufferRef.current = "";
                  }
                }, 300);
              }

              // Extract memory tags
              const memoryMatches = [...outputText.matchAll(/\[REMEMBER:\s*(.*?)\]/gi)];
              if (memoryMatches.length > 0) {
                const newMemories = memoryMatches.map(m => m[1]);
                setMemories(prev => {
                  const updated = [...prev, ...newMemories];
                  localStorage.setItem('shakti_memories', JSON.stringify(updated));
                  return updated;
                });
                // Remove tags from output text
                outputText = outputText.replace(/\[REMEMBER:\s*(.*?)\]/gi, '').trim();
              }

              if (outputText) {
                setMessages(prev => {
                  const last = prev[prev.length - 1];
                  if (last && last.role === 'mj') {
                    return [...prev.slice(0, -1), { ...last, text: last.text + outputText }];
                  }
                  return [...prev, { id: Date.now().toString(), role: 'mj', text: outputText }];
                });
              }
            }
            
            // Handle Grounding Metadata (Search Links)
            const groundingChunks = message.serverContent?.modelTurn?.groundingMetadata?.groundingChunks || message.serverContent?.groundingMetadata?.groundingChunks;
            if (groundingChunks && groundingChunks.length > 0) {
              const links = groundingChunks
                .map((chunk: any) => chunk.web?.uri ? `\n[Source: ${chunk.web.title || chunk.web.uri}](${chunk.web.uri})` : '')
                .filter(Boolean)
                .join('');
                
              if (links) {
                setMessages(prev => {
                  const last = prev[prev.length - 1];
                  if (last && last.role === 'mj') {
                    // Avoid duplicating links
                    if (!last.text.includes(links.trim())) {
                       return [...prev.slice(0, -1), { ...last, text: last.text + '\n' + links }];
                    }
                    return prev;
                  }
                  return [...prev, { id: Date.now().toString(), role: 'mj', text: links }];
                });
              }
            }
            
            if (message.serverContent?.interrupted) {
              audioStreamerRef.current?.stop();
              setIsSpeaking(false);
            }
          },
          onclose: () => disconnect(),
          onerror: (err: any) => {
            console.error("Live API Error:", err);
            const errorMessage = err.message || String(err);
            if (errorMessage.includes('quota') || errorMessage.includes('429')) {
              setError("API Quota Exceeded. Please check your Google AI Studio billing details or add a valid API key in Settings.");
            } else if (errorMessage.includes('Network error') || err instanceof Event) {
              setError("Network error: Lost connection to MAX servers.");
            } else {
              setError("Connection error: " + errorMessage);
            }
            disconnect();
          }
        }
      }).catch(err => {
        console.error("Session Connection Failed:", err);
        setError("Failed to initialize neural link. Verify your API key.");
        setIsConnecting(false);
        setIsConnected(false);
        throw err;
      });

      sessionRef.current = await sessionPromise;
    } catch (err: any) {
      console.error("Failed to connect:", err);
      const errorMessage = err.message || String(err);
      if (errorMessage.includes('quota') || errorMessage.includes('429')) {
        setError("API Quota Exceeded. Please check your Google AI Studio billing details or add a valid API key in Settings.");
      } else {
        setError(errorMessage || "Failed to connect to MJ.");
      }
      setIsConnecting(false);
      disconnect();
    }
  }, [isConnected, isConnecting, memories, disconnect, clearMemories, startVideo, stopVideo, uiControls, generateSong, setGeneratedSong, setActiveChart, setAppVolume]);

  // Wake Word Logic
  useEffect(() => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      console.warn("Speech recognition not supported in this browser.");
      return;
    }

    if (wakeWordEnabled && !isConnected && !isConnecting) {
      if (!recognitionRef.current) {
        const recognition = new SpeechRecognition();
        recognition.continuous = false; // Better for mobile
        recognition.interimResults = true;
        recognition.lang = 'en-US'; // Force English for wake word
        
        recognition.onstart = () => setIsListeningForWakeWord(true);
        
        recognition.onerror = (event: any) => {
          console.warn("Speech recognition error:", event.error);
          setIsListeningForWakeWord(false);
          if (wakeWordEnabled && !isConnected && !isConnecting && event.error !== 'aborted') {
            setTimeout(() => {
              try { recognition.start(); } catch (e) {}
            }, 1000);
          }
        };

        recognition.onend = () => {
          setIsListeningForWakeWord(false);
          // Restart if still supposed to be listening
          if (wakeWordEnabled && !isConnected && !isConnecting) {
            setTimeout(() => {
              try { recognition.start(); } catch (e) {}
            }, 500);
          }
        };
        
        recognition.onerror = (event: any) => {
          if (event.error === 'not-allowed' || event.error === 'service-not-allowed') {
            setWakeWordEnabled(false);
          }
        };
        
        recognition.onresult = (event: any) => {
          let transcript = '';
          for (let i = event.resultIndex; i < event.results.length; i++) {
            transcript += event.results[i][0].transcript.toLowerCase();
          }
          
          console.log("Wake word transcript:", transcript);
            
          const match = transcript.match(WAKE_WORD_REGEX);
          if (match) {
            console.log("Wake word detected!");
            const command = transcript.split(match[0])[1]?.trim();
            recognition.stop();
            connect(command || undefined);
          }
        };
        
        recognitionRef.current = recognition;
      }
      
      try {
        recognitionRef.current.start();
      } catch (e) {
        // Already started
      }
    } else {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
        setIsListeningForWakeWord(false);
      }
    }

    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, [wakeWordEnabled, isConnected, isConnecting, connect]);

  // Poll MJ Volume
  useEffect(() => {
    let raf: number;
    const poll = () => {
      if (isSpeaking && audioStreamerRef.current) {
        setMjVolume(audioStreamerRef.current.getVolume());
      } else {
        setMjVolume(0);
      }
      raf = requestAnimationFrame(poll);
    };
    raf = requestAnimationFrame(poll);
    return () => cancelAnimationFrame(raf);
  }, [isSpeaking]);

  const sendText = (text: string) => {
    if (!sessionRef.current) return;
    sessionRef.current.sendRealtimeInput({ text });
    setMessages(prev => [...prev, { id: Date.now().toString(), role: 'user', text }]);
  };

  const toggleCamera = () => {
    if (activeVideoSource === 'camera') stopVideo();
    else startVideo('camera');
  };

  const toggleScreen = () => {
    if (activeVideoSource === 'screen') stopVideo();
    else startVideo('screen');
  };

  const flipCamera = () => {
    setFacingMode(prev => {
      const next = prev === 'user' ? 'environment' : 'user';
      if (activeVideoSource === 'camera') {
        setTimeout(() => startVideo('camera', next), 0);
      }
      return next;
    });
  };

  useEffect(() => {
    return () => disconnect();
  }, [disconnect]);

  const testVoice = () => {
    if (audioStreamerRef.current) {
      audioStreamerRef.current.resume();
      // Play a short beep or silence to trigger context resume
      const ctx = (audioStreamerRef.current as any).audioCtx;
      if (ctx) {
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.connect(gain);
        gain.connect(ctx.destination);
        gain.gain.setValueAtTime(0, ctx.currentTime);
        osc.start();
        osc.stop(ctx.currentTime + 0.1);
      }
    }
    
    if (voice === 'ElevenLabs') {
      const puterInstance = (window as any).puter;
      if (puterInstance && puterInstance.ai) {
        const ai = puterInstance.ai;
        const ttsMethod = (ai.tts || ai.textToSpeech || ai.speak)?.bind(ai);
        
        if (typeof ttsMethod === 'function') {
          ttsMethod("नमस्ते, मैं आपकी सहायता के लिए तैयार हूँ।", 'rachel').then((audio: any) => {
            if (audio instanceof HTMLAudioElement) audio.play();
            else if (audio instanceof Blob) new Audio(URL.createObjectURL(audio)).play();
          }).catch((e: any) => console.error("Test voice failed:", e));
        } else {
          console.error("Puter TTS: No TTS method found on puter.ai. Available keys:", Object.keys(ai));
        }
      }
    } else {
      setError("Native voice test: Please speak to MAX to hear a response.");
      setTimeout(() => setError(null), 3000);
    }
  };

  return {
    isConnected,
    isConnecting,
    isSpeaking,
    isListeningForWakeWord,
    wakeWordEnabled,
    setWakeWordEnabled,
    memories,
    clearMemories,
    error,
    activeVideoSource,
    userVolume,
    mjVolume,
    messages,
    sendText,
    connect,
    disconnect,
    toggleCamera,
    toggleScreen,
    flipCamera,
    videoRef,
    canvasRef,
    generatedSong,
    setGeneratedSong,
    activeChart,
    setActiveChart,
    appVolume,
    setAppVolume,
    voice,
    setVoice,
    testVoice,
    isScreenShareSupported: !!(typeof navigator !== 'undefined' && navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia)
  };
}
